platform :android do
  desc "Release Beta version of Docdoc application to Android testers"
  lane :distribute_android do
      sh "flutter clean"
      sh "flutter pub get"
      sh "flutter build apk --release --flavor production --target=lib/main_production.dart --no-tree-shake-icons"
      release = firebase_app_distribution(
          app: "1:342952968443:android:2b42c56108611865e8305e",
          testers: "ahmedabdelrahman4999@gmail.com, ahmedghwalby@gmail.com",
          release_notes: "Appling Authentication Flow for Android DocDoc Application",
          firebase_cli_token:ENV['FIREBASE_CLI_REFRESH_TOKEN'],
          android_artifact_type: "APK",
          android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk"
      )
  end
end
